import type { ReuseStream } from './deconstructionTypes';

export interface InspectionShot {
  id: string;
  zone:
    | 'exterior-south'
    | 'exterior-north'
    | 'exterior-east'
    | 'exterior-west'
    | 'attic'
    | 'ground-floor'
    | 'cellar'
    | 'roof-surface'
    | 'junction';
  index: number;
  subject: string;
  standoff: string;
  angle: string;
  reference: string;
  captureSeries: string;
  laserMeasurement: string;
  reconstructionUse: string;
  purpose: string;
  linkedTaskIds: string[];
  linkedReuseStreams: ReuseStream[];
}

export const reconstructionCaptureProtocol = [
  'Pro S-Position mehrere Fotos aufnehmen: ein Übersichtsbild, zwei bis vier leicht seitlich versetzte Bilder und Detailbilder nur nach der Übersicht.',
  'Die Kamera zwischen den Bildern nur klein versetzen oder leicht schwenken; 60-80 % Überlappung anstreben.',
  'Zu jedem S-Block mindestens eine Laserdistanz vom Foto-Standort zu einem eindeutig sichtbaren Referenzpunkt protokollieren.',
  'Referenzpunkte als feste Gebäudepunkte wählen: Mauerecke, Schwelle, Fensterlaibung, Trauf-/Ortgangpunkt, Sparrenkante. Keine beweglichen Teile, Vegetation oder lose Gegenstände verwenden.',
  'Belichtung und Fokus möglichst konstant halten; reflektierende Glasflächen, bewegte Personen und sehr starke Weitwinkelverzerrung vermeiden.',
] as const;

export const inspectionShotList: InspectionShot[] = [
  {
    id: 'S01',
    zone: 'exterior-south',
    index: 1,
    subject: 'Südseite Part 1: vollständige Fassadenansicht',
    standoff: 'Ca. 6-10 m Abstand, Standpunkt mittig vor der Fassade, danach je ein Schritt nach links und rechts.',
    angle: 'Kamera waagerecht, komplette Höhe von Gelände/Sockel bis Traufe aufnehmen.',
    reference: 'Feste südliche Gebäudeecke oder untere Außenecke einer sichtbaren Schwelle als Referenzpunkt.',
    captureSeries: '5-7 Fotos: Mitte, links, rechts, leicht schräg links, leicht schräg rechts, optional Sockel- und Traufen-Detail.',
    laserMeasurement: 'Laserdistanz vom Hauptstandpunkt zum gewählten Referenzpunkt messen; Referenzpunkt im Foto sichtbar halten.',
    reconstructionUse: 'Grundlage für Fassadenebene, Fensterpositionen, Geländeanschluss und spätere Skalierung der Südansicht.',
    purpose: 'Fassadenzustand, Öffnungen, Geländeanschluss, Feuchte- und Putzspuren dokumentieren.',
    linkedTaskIds: ['south-wall-condition', 'wall-openings', 'wall-thickness'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S02',
    zone: 'exterior-south',
    index: 2,
    subject: 'Südseite Part 1: Sockel, Spritzwasserzone und Geländeanschluss',
    standoff: 'Ca. 1-2 m Abstand, Kamera auf Knie- bis Hüfthöhe entlang des Sockels führen.',
    angle: 'Leicht nach unten, Wand/Gelände-Fuge und sichtbare Schadenshöhe erfassen.',
    reference: 'Untere Mauerecke, Schwellenkante oder klarer Putz-/Sockelversatz; Maßstab oder Zollstock zusätzlich sichtbar platzieren.',
    captureSeries: '6-10 Fotos als kurze Sequenz entlang des Sockels mit starker Überlappung; Schadstellen zusätzlich frontal und schräg.',
    laserMeasurement: 'Distanz vom ersten Sockel-Standpunkt zum festen Referenzpunkt messen und notieren, welche Fotos zu dieser Messung gehören.',
    reconstructionUse: 'Hilft bei Sockelband, Feuchtehöhe, Geländekante und späterer Materialklassifikation.',
    purpose: 'Feuchte, Salz, Frostschäden, Putzablösungen und direkte Wasserbelastung am Sockel erfassen.',
    linkedTaskIds: ['south-wall-condition', 'cellar-moisture'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S03',
    zone: 'exterior-south',
    index: 3,
    subject: 'Südliche Dachfläche Part 1: Gesamtansicht',
    standoff: 'Ca. 10-15 m Abstand von sicherem Standort, möglichst mit Blick auf komplette Dachfläche.',
    angle: 'Nach oben geneigt, Traufe, Ortgang, Firstprojektion und Dachfläche vollständig sichtbar.',
    reference: 'Fester Traufpunkt oder südliche Gebäudeecke; wenn nicht erreichbar, sichtbarer Ortgangpunkt.',
    captureSeries: '5-8 Fotos: Gesamtfläche mittig, links/rechts versetzt, Traufe, First/Ortgang und sichtbare Durchdringungen.',
    laserMeasurement: 'Distanz zum gewählten Fassaden-/Traufreferenzpunkt messen, nicht zu Dachziegeln ohne eindeutigen Zielpunkt.',
    reconstructionUse: 'Verbessert Dachflächenrekonstruktion, PV-Flächenprüfung, Hinderniserkennung und Dachneigungsabgleich.',
    purpose: 'Dacheindeckung, Zustand, Durchdringungen, Schatten und PV-relevante Störungen dokumentieren.',
    linkedTaskIds: ['roof-obstructions', 'pv-usable-area'],
    linkedReuseStreams: ['timber', 'finishes'],
  },
  {
    id: 'S04',
    zone: 'exterior-south',
    index: 4,
    subject: 'Südliche Dachfläche Part 2: Gesamtansicht und Anschlusskontext',
    standoff: 'Ca. 8-12 m Abstand, sicherer Standort mit Sicht auf Part 2 und Anschluss zu Part 1.',
    angle: 'Dachfläche, Traufe, Firstlinie und Übergang zu Part 1 erfassen.',
    reference: 'Feste Ecke oder Traufkante von Part 2; Referenzpunkt muss in mindestens einem Foto klar sichtbar sein.',
    captureSeries: '5-8 Fotos mit überlappenden Blickwinkeln, davon mindestens zwei mit Part-1/Part-2-Übergang.',
    laserMeasurement: 'Distanz vom Hauptstandpunkt zum Referenzpunkt an Part 2 messen; bei Übergangsfoto zusätzlich Referenzpunkt benennen.',
    reconstructionUse: 'Nützlich für Vergleich der Dachflächen, Anschlussgeometrie, Höhenbeziehung und PV-Kontext.',
    purpose: 'Dachzustand, Hindernisse und konstruktive Beziehung zwischen Part 1 und Part 2 erfassen.',
    linkedTaskIds: ['roof-obstructions', 'roof-ridge-length'],
    linkedReuseStreams: ['timber', 'finishes'],
  },
  {
    id: 'S05',
    zone: 'exterior-north',
    index: 5,
    subject: 'Nordseite: vollständige Fassadenansicht und Hangkontakt',
    standoff: 'Ca. 5-10 m Abstand, soweit Gelände und Vegetation es zulassen.',
    angle: 'Kamera waagerecht, komplette Wandhöhe plus sichtbaren Boden-/Hangbereich aufnehmen.',
    reference: 'Feste nordseitige Mauerecke, Sockelpunkt oder klarer Wand-/Gelände-Kontaktpunkt.',
    captureSeries: '5-9 Fotos: frontal, seitlich links/rechts, Hang-/Sockelzone und Dach-/Traufbereich.',
    laserMeasurement: 'Distanz zum festen Referenzpunkt messen; Behinderungen durch Bewuchs im Protokoll notieren.',
    reconstructionUse: 'Hilft bei Rekonstruktion der Nordfassade, Hangnähe, Verschattung und Feuchterisiko.',
    purpose: 'Nordwandzustand, Entwässerung, Hangnähe, Algen-/Feuchtespuren und Schattenlinie erfassen.',
    linkedTaskIds: ['drainage', 'pv-shading'],
    linkedReuseStreams: ['masonry', 'documentation'],
  },
  {
    id: 'S06',
    zone: 'exterior-north',
    index: 6,
    subject: 'Nordseite: Baumlinie, Verschattung und Abstand zum Gebäude',
    standoff: 'Ca. 15-25 m, so dass Baumhöhe, Kronenbreite und Gebäude gemeinsam oder in Folgefotos sichtbar sind.',
    angle: 'Waagerecht bis leicht nach oben, Baumfuß und Baumkrone möglichst in einer Sequenz erfassen.',
    reference: 'Baumfuß eines eindeutig identifizierbaren Baums oder fester Gebäudepunkt am nächstliegenden Wandabschnitt.',
    captureSeries: '5-8 Fotos als Bogen: Baumlinie links, Mitte, rechts, zusätzlich ein Foto mit Gebäude als Bezug.',
    laserMeasurement: 'Distanz zum Baumfuß oder zum gewählten Gebäudepunkt messen; Zielpunkt eindeutig im Foto markieren/beschreiben.',
    reconstructionUse: 'Unterstützt spätere Verschattungsabschätzung, Höhenableitung und PV-Ertragsrisiko.',
    purpose: 'Baumhöhe, Abstand, Kronenausladung und saisonale Verschattungsrisiken dokumentieren.',
    linkedTaskIds: ['pv-shading'],
    linkedReuseStreams: ['documentation'],
  },
  {
    id: 'S07',
    zone: 'exterior-east',
    index: 7,
    subject: 'Ostansicht Part 1: Giebel/Fassade und Eingang links neben Wintergarten',
    standoff: 'Ca. 6-10 m Abstand; zusätzlich schräg vom Wintergarten/Flur-Anschluss aufnehmen.',
    angle: 'Komplette Höhe von Sockel bis First/Ortgang; Eingangsschwelle und Gelände sichtbar lassen.',
    reference: 'Untere Außenecke der EG-Eingangsschwelle links neben dem Wintergarten oder harte Giebel-Mauerecke.',
    captureSeries: '7-10 Fotos: Hauptansicht, links/rechts versetzt, Eingang, Geländeanschluss, Traufe/Ortgang, Anschluss Wintergarten/Flur.',
    laserMeasurement: 'Distanz vom Hauptfoto-Standpunkt zur Eingangsschwellen-Ecke messen; bei Schrägfotos gleiche Referenz verwenden, wenn sichtbar.',
    reconstructionUse: 'Wichtig für A-01, Gelände-/EG-Bezug, Fassadenebene und Part-1-Untergliederung.',
    purpose: 'Giebelzustand, Wand-/Dachanschluss, Eingangsniveau, Gelände und Anschluss zu Wintergarten/Flur prüfen.',
    linkedTaskIds: ['wall-thickness', 'roof-ridge-length'],
    linkedReuseStreams: ['masonry', 'timber'],
  },
  {
    id: 'S08',
    zone: 'exterior-west',
    index: 8,
    subject: 'Westansicht Part 1: Giebel, Erkerseite und Wetterseite',
    standoff: 'Ca. 6-10 m Abstand, eine frontale und mehrere schräg versetzte Positionen wählen.',
    angle: 'Komplette Höhe von Sockel bis First; Erkerlage und westliche Dach-/Wandkante sichtbar halten.',
    reference: 'Südwestliche harte Gebäudeecke, Erker-Mauerecke oder klarer Ortgang-/Sockelpunkt.',
    captureSeries: '7-10 Fotos: Giebel frontal, Erkeranschluss, Sockel, Öffnungen, Traufe/Ortgang, schräge Wetterseiten-Perspektiven.',
    laserMeasurement: 'Distanz zum gewählten festen Referenzpunkt messen; bei Erkerdetail separaten Referenzpunkt notieren.',
    reconstructionUse: 'Wichtig für Erker-Korrektur, Wetterseitenrisiko, Giebelbreite und spätere 3D-Dichte.',
    purpose: 'Westseitige Schlagregenbelastung, Erkeranschluss, Öffnungen und Wand-/Dachdetails dokumentieren.',
    linkedTaskIds: ['wall-thickness'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S09',
    zone: 'junction',
    index: 9,
    subject: 'Außenanschluss Part 1 zu Part 2',
    standoff: 'Ca. 4-8 m Abstand, so dass beide Baukörper und die Fuge gemeinsam sichtbar sind.',
    angle: 'Schräg auf die Anschlusszone, Höhenversatz, Dachlinien, Wandfuge und Gelände gemeinsam zeigen.',
    reference: 'Fester unterer Eckpunkt am Part-1/Part-2-Anschluss oder sichtbare Schwelle/Stufe im Anschlussbereich.',
    captureSeries: '8-12 Fotos: frontal zur Fuge, schräg von beiden Seiten, Sockel, Dach-/Traufanschluss, Detailfotos der Fuge.',
    laserMeasurement: 'Distanz vom Hauptstandpunkt zum Anschluss-Referenzpunkt messen; bei beidseitigen Schrägfotos Zielpunkt gleich halten.',
    reconstructionUse: 'Erhöht Wert für Bauteiltrennung, Höhenversatz, Verformung und spätere Sanierungsvarianten.',
    purpose: 'Konstruktive Verbindung, Risse, Niveauversatz, Anschlüsse und Wasserfallen am Übergang beurteilen.',
    linkedTaskIds: ['wall-thickness', 'south-wall-condition'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S10',
    zone: 'junction',
    index: 10,
    subject: 'Innenanschluss Part 1 zu Part 2, falls zugänglich',
    standoff: 'Innenraum, ca. 1-3 m Abstand zur Verbindungswand oder Öffnung.',
    angle: 'Wand/Öffnung vollständig mit Boden- und Deckenanschluss zeigen.',
    reference: 'Feste Laibungsecke, Sturzkante oder Schwellenkante im Verbindungsbereich.',
    captureSeries: '5-8 Fotos: Gesamtöffnung, linke/rechte Laibung, Sturz, Schwelle, angrenzende Wandflächen.',
    laserMeasurement: 'Distanz vom Foto-Standpunkt zur Laibungs-/Schwellenkante messen und Foto-ID zuordnen.',
    reconstructionUse: 'Hilft bei Innen-/Außenabgleich, tragender Wandhypothese und Anschlussmodell.',
    purpose: 'Tragende Wand, Öffnung, Materialwechsel, Höhenversatz und Feuchtespuren am Innenanschluss prüfen.',
    linkedTaskIds: ['wall-thickness', 'roof-structure'],
    linkedReuseStreams: ['masonry', 'timber'],
  },
  {
    id: 'S11',
    zone: 'attic',
    index: 11,
    subject: 'Dachgeschoss/Attic Part 1: Übersicht entlang der First-/Hauptrichtung',
    standoff: 'Im Dachraum sicherer Standpunkt an einem Ende, Blick entlang der Hauptachse.',
    angle: 'Waagerecht bis leicht nach oben; Sparrenfelder, Pfetten, Firstbereich und Bodenbezug zeigen.',
    reference: 'Feste Sparrenkante, Pfettenauflager oder Giebelinnenecke; Maßband über ein Sparrenfeld sichtbar.',
    captureSeries: '6-10 Fotos entlang der Achse: Übersicht, links/rechts versetzt, beide Dachflächen, Auflager, Firstbereich.',
    laserMeasurement: 'Distanz vom Standpunkt zur gewählten Sparren-/Pfettenkante messen; Zielpunkt in Foto sichtbar halten.',
    reconstructionUse: 'Gute Basis für Innenraum-Splatting, Dachtragwerk, Sparrenabstände und Dachneigungsableitung.',
    purpose: 'Dachstruktur, Sparren/Pfetten, Belüftung, Feuchtespuren und Geometrie des Dachraums erfassen.',
    linkedTaskIds: ['roof-structure', 'roof-pitch'],
    linkedReuseStreams: ['timber'],
  },
  {
    id: 'S12',
    zone: 'attic',
    index: 12,
    subject: 'Sparrenquerschnitt und Sparrenabstand',
    standoff: 'Ca. 0.5-1 m Abstand zum Sparren, genug Umfeld für Einordnung sichtbar lassen.',
    angle: 'Seitlich auf den Sparrenquerschnitt, mit sichtbarem Maßstab und angrenzendem Sparrenfeld.',
    reference: 'Sparrenkante oder Maßband-Anfangspunkt am Holzquerschnitt.',
    captureSeries: '4-6 Fotos: Querschnitt frontal, schräg, mit Maßband, Anschluss an Dachhaut, Umfeldfoto.',
    laserMeasurement: 'Distanz zur Sparrenkante messen, wenn der Standpunkt eindeutig bleibt; sonst Messung als Detailfoto ohne Georeferenz kennzeichnen.',
    reconstructionUse: 'Hilft bei Maßskalierung des Tragwerks und bei Material-/Wiederverwendungsbewertung.',
    purpose: 'Holzquerschnitt, Abstand, Zustand und mögliche Wiederverwendung dokumentieren.',
    linkedTaskIds: ['roof-structure'],
    linkedReuseStreams: ['timber'],
  },
  {
    id: 'S13',
    zone: 'attic',
    index: 13,
    subject: 'Pfette-Sparren-Verbindung und Holzverbindungen',
    standoff: 'Ca. 0.5-1 m Abstand, Verbindung vollständig und mit Umgebung aufnehmen.',
    angle: 'Schräg, so dass Kerbe, Nagelung, Verschraubung oder Zapfung erkennbar ist.',
    reference: 'Pfettenkante, Sparrenkante oder klarer Verbindungspunkt; kleiner Maßstab daneben.',
    captureSeries: '5-7 Fotos: Gesamtverbindung, linke/rechte Seite, Unterseite, Detail mit Maßstab, Umfeldbezug.',
    laserMeasurement: 'Distanz zum Verbindungspunkt messen, falls sicher anvisierbar; ansonsten Referenz über S11 übernehmen und Detail zuordnen.',
    reconstructionUse: 'Nützlich für Bauteilsemantik und spätere Einschätzung, ob zerstörungsarme Demontage möglich ist.',
    purpose: 'Verbindungsart, Zustand und Rückbau-/Wiederverwendungspotenzial beurteilen.',
    linkedTaskIds: ['roof-structure'],
    linkedReuseStreams: ['timber'],
  },
  {
    id: 'S14',
    zone: 'attic',
    index: 14,
    subject: 'Schlechteste sichtbare Holzstelle im Dachraum',
    standoff: 'Nahaufnahme und ein Umfeldfoto; Kamera nicht nur auf den Schaden isolieren.',
    angle: 'Schadenslänge, Faserrichtung, Auflagerbezug und angrenzende Bauteile zeigen.',
    reference: 'Feste Bauteilkante am beschädigten Holz; Stift, Zollstock oder Maßstab sichtbar.',
    captureSeries: '5-8 Fotos: Umfeld, Schaden frontal, schräg, Maßstab, Auflager/Anschluss, ggf. Feuchtequelle.',
    laserMeasurement: 'Distanz zum Schadens-Referenzpunkt messen, wenn vom gleichen Standpunkt möglich; sonst Distanz aus S11/S13 zuordnen.',
    reconstructionUse: 'Erlaubt spätere Lokalisierung kritischer Stellen im 3D-Modell statt isolierter Schadensfotos.',
    purpose: 'Fäulnis, Insekten, Risse, Durchbiegung oder alte Leckage als Ausschlusskriterien dokumentieren.',
    linkedTaskIds: ['roof-structure'],
    linkedReuseStreams: ['timber'],
  },
  {
    id: 'S15',
    zone: 'attic',
    index: 15,
    subject: 'Dachgeschoss/Attic Part 2: Übersicht entlang der First-/Hauptrichtung',
    standoff: 'Sicherer Standpunkt im Dachraum Part 2, Blick entlang der Hauptachse.',
    angle: 'Waagerecht entlang der Tragstruktur, möglichst First, Sparren, Pfetten und Auflager sichtbar.',
    reference: 'Feste Sparrenkante, Pfettenauflager oder Giebelinnenecke in Part 2.',
    captureSeries: '6-10 Fotos: Übersicht, seitlich versetzt, beide Dachflächen, Auflager, Anschlussrichtung zu Part 1.',
    laserMeasurement: 'Distanz vom Standpunkt zum gewählten festen Tragwerks-Referenzpunkt messen.',
    reconstructionUse: 'Vergleichsbasis für Dachsystem Part 1/Part 2 und mögliche gemeinsame Dach-/Hüllvarianten.',
    purpose: 'Tragwerksvergleich, Dachzustand, Höhenbezug und Plausibilität eines vereinheitlichten Dachkonzepts erfassen.',
    linkedTaskIds: ['roof-structure', 'roof-pitch'],
    linkedReuseStreams: ['timber'],
  },
  {
    id: 'S16',
    zone: 'ground-floor',
    index: 16,
    subject: 'Erdgeschoss Part 1: Innenwand Südseite und Feuchtebild',
    standoff: 'Ca. 1-3 m Abstand zur Innenwand, möglichst mit Boden- und Deckenanschluss.',
    angle: 'Waagerecht, ganze Wandhöhe; Detailfotos nur mit Umfeldbezug.',
    reference: 'Feste Innenecke, Schwellenkante oder markierter Feuchte-Messpunkt auf der Wand.',
    captureSeries: '5-8 Fotos: Wandübersicht, Sockelbereich, Feuchteflecken, Öffnungsnähe, Messpunkte mit Markierung.',
    laserMeasurement: 'Distanz vom Foto-Standpunkt zur Innenecke oder zum markierten Messpunkt erfassen.',
    reconstructionUse: 'Hilft bei Innen-/Außenabgleich, Feuchtehöhe und Verortung von Messpunkten.',
    purpose: 'Innenfeuchte, Putzschäden, Salz, Schimmelverdacht und Wandaufbauhinweise dokumentieren.',
    linkedTaskIds: ['cellar-moisture', 'wall-thickness'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S17',
    zone: 'ground-floor',
    index: 17,
    subject: 'Wandstärkenmessung an Fenster- oder Türlaibung',
    standoff: 'Innen an einer geöffneten Laibung, ca. 0.5-1.5 m Abstand.',
    angle: 'Entlang der Laibung, Maßband von Innenkante bis Außenkante sichtbar.',
    reference: 'Innere Laibungsecke oder Anfangspunkt des Maßbands.',
    captureSeries: '4-6 Fotos: Laibung gesamt, Maßband lesbar, Innenkante, Außenkante, Umfeldfoto zur Zuordnung.',
    laserMeasurement: 'Distanz vom Foto-Standpunkt zur inneren Laibungsecke messen; genaue Wandstärke zusätzlich als Maß notieren.',
    reconstructionUse: 'Skaliert Wandstärke, Öffnungstiefe und hilft, das CAD-Seed mit realen Wanddicken zu korrigieren.',
    purpose: 'Primäre Wandstärkenprüfung für U-Wert, Materialmenge und Wiederverwendungsvolumen.',
    linkedTaskIds: ['wall-thickness'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S18',
    zone: 'cellar',
    index: 18,
    subject: 'Kellergewölbe: Gesamtübersicht und Gewölberichtung',
    standoff: 'Sicherer Kellerstandpunkt in einer Ecke oder an der Tür, diagonal durch den Raum.',
    angle: 'Möglichst Decke/Gewölbe, Wände und Boden gleichzeitig aufnehmen.',
    reference: 'Feste Kellerecke, Türschwelle oder Beginn der Gewölbeachse; Maßband am Boden sichtbar.',
    captureSeries: '6-10 Fotos: diagonal, Gegendiagonal, Längsrichtung Gewölbe, Boden, Decke, Eingang/Schwelle.',
    laserMeasurement: 'Distanz vom Hauptstandpunkt zur Kellerecke oder Türschwelle messen; Sicherheitszugang nicht gefährden.',
    reconstructionUse: 'Wichtig für Kellerlage, Gewölberichtung, Raumvolumen und Innen-/Außenbezug am südlichsten Eck.',
    purpose: 'Feuchteausdehnung, Boden, Gewölbe, Raumhöhe und tragende Wandbereiche dokumentieren.',
    linkedTaskIds: ['cellar-moisture', 'drainage'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S19',
    zone: 'cellar',
    index: 19,
    subject: 'Keller: stärkste Feuchte- oder Salzschadenszone',
    standoff: 'Ca. 0.5-1.5 m Abstand, erst Umfeld, dann Detail.',
    angle: 'Wandfläche von Boden bis oberhalb Schadensgrenze aufnehmen.',
    reference: 'Feste Wandecke oder markierte Oberkante der Feuchte-/Salzzone; Maßstab vertikal sichtbar.',
    captureSeries: '5-8 Fotos: Wandübersicht, Schadensband, Maßstab, Bodenanschluss, Gewölbe-/Wandanschluss.',
    laserMeasurement: 'Distanz zur Wandecke oder markierten Schadensoberkante messen; Zielpunkt beschreiben.',
    reconstructionUse: 'Macht Feuchtehöhe im 3D-Kontext auswertbar statt nur als isoliertes Schadensbild.',
    purpose: 'Feuchteanstieg, Salz, Putz-/Mauerwerksschaden und Sanierungsdringlichkeit quantifizieren.',
    linkedTaskIds: ['cellar-moisture'],
    linkedReuseStreams: ['masonry'],
  },
  {
    id: 'S20',
    zone: 'roof-surface',
    index: 20,
    subject: 'Dacheindeckung: repräsentativer Ziegel-/Deckungszustand',
    standoff: 'Nur von sicherem Dachzugang, Leiterstand oder Innen-/Fensterposition; nicht riskant betreten.',
    angle: 'Nahaufnahme mit Umgebung: mindestens drei zusammenhängende Deckelemente, Überdeckung und Bruchstellen zeigen.',
    reference: 'Feste Kante eines Dachziegels, Ortgang-/Traufkante oder sichtbarer Maßstab auf gleicher Ebene.',
    captureSeries: '5-8 Fotos: repräsentative Fläche, schlechteste Stelle, Überdeckung, Kante, Maßstab, Umfeld zur Dachfläche.',
    laserMeasurement: 'Distanz nur messen, wenn sicher und eindeutig anvisierbar; sonst S03/S04 als Lagekontext nutzen und Detail als Nahserie kennzeichnen.',
    reconstructionUse: 'Ergänzt Makro-Textur, Materialzustand, Frostschäden und Klassifikation für Wiederverwendung oder Austausch.',
    purpose: 'Dachdeckungszustand, Risse, Frostschäden, Mörtelbettung und Wiederverwendungspotenzial beurteilen.',
    linkedTaskIds: ['roof-obstructions'],
    linkedReuseStreams: ['finishes'],
  },
];
