import type { DataInventoryItem } from '@/domain/AddressProject';

export const dataInventorySeed: DataInventoryItem[] = [
  {
    id: 'geocoding-manual',
    label: 'Manual location',
    sourceName: 'Local private configuration',
    status: 'candidate',
    confidence: 'high',
    notes: 'Exact address and coordinates must remain local only.',
  },
  {
    id: 'nominatim',
    label: 'Address geocoding',
    sourceName: 'Nominatim / OpenStreetMap',
    sourceUrl: 'https://nominatim.org/',
    status: 'unchecked',
    confidence: 'medium',
  },
  {
    id: 'photon',
    label: 'Street search suggestions',
    sourceName: 'Photon / Komoot',
    sourceUrl: 'https://photon.komoot.io/',
    status: 'unchecked',
    confidence: 'medium',
  },
  {
    id: 'lod2-bayern',
    label: 'LoD2 building model',
    sourceName: 'Bayerische Vermessungsverwaltung / LDBV',
    sourceUrl: 'https://www.ldbv.bayern.de/vermessung/zshh/lod2-de.html',
    status: 'candidate',
    confidence: 'medium',
    licenseHint: 'Check current LDBV terms before redistribution.',
    notes: 'Use for building hull baseline only. Not structural truth.',
  },
  {
    id: 'dgm1-bayern',
    label: 'DGM1 terrain model',
    sourceName: 'Bayerische Vermessungsverwaltung / LDBV',
    status: 'candidate',
    confidence: 'high',
    notes: 'Use for slope, drainage and terrain context.',
  },
  {
    id: 'energie-atlas-bayern',
    label: 'Solar potential context',
    sourceName: 'Energie-Atlas Bayern',
    sourceUrl: 'https://www.energieatlas.bayern.de/',
    status: 'unchecked',
    confidence: 'medium',
  },
  {
    id: 'pvgis',
    label: 'Solar irradiation and PV yield',
    sourceName: 'PVGIS / EU JRC',
    sourceUrl: 'https://joint-research-centre.ec.europa.eu/pvgis-online-tool_en',
    status: 'unchecked',
    confidence: 'high',
  },
  {
    id: 'dwd-try',
    label: 'Test reference years',
    sourceName: 'Deutscher Wetterdienst TRY',
    sourceUrl: 'https://www.dwd.de/DE/leistungen/testreferenzjahre/testreferenzjahre.html',
    status: 'unchecked',
    confidence: 'high',
  },
  {
    id: 'copernicus-era5',
    label: 'Climate reanalysis',
    sourceName: 'Copernicus ERA5 / ERA5-Land',
    sourceUrl: 'https://climate.copernicus.eu/',
    status: 'unchecked',
    confidence: 'medium',
  },
  {
    id: 'denkmalatlas-bayern',
    label: 'Heritage constraints',
    sourceName: 'Bayerischer Denkmal-Atlas',
    sourceUrl: 'https://www.blfd.bayern.de/denkmal-atlas/',
    status: 'candidate',
    confidence: 'high',
    notes: 'Queried 2026-05-11. Building NOT listed. Nearest Baudenkmal: Kapelle 212 m west (consultation required for permits). Nearest Bodendenkmal: frühe Neuzeit 207 m west (no consultation, but report deep earthworks to BLfD).',
  },
  {
    id: 'alkis-flurstueck',
    label: 'ALKIS cadastral parcel (Flurstück)',
    sourceName: 'ADBV Nabburg / Bayerische Vermessungsverwaltung',
    sourceUrl: 'https://geodatenonline.bayern.de',
    status: 'downloaded',
    confidence: 'high',
    notes: 'Flurkarte 1:500 erhalten. Gültig für Bauvorlage (§ 7 Abs. 1 BauVorlV). Grundriss und Parzellengrenze sichtbar im Maßstab 1:500. Details in Projektdokumentation.',
  },
  {
    id: 'umweltatlas-bayern',
    label: 'Environmental and natural risk context',
    sourceName: 'UmweltAtlas Bayern',
    sourceUrl: 'https://www.lfu.bayern.de/umweltdaten/kartendienste/umweltatlas/',
    status: 'unchecked',
    confidence: 'medium',
  },
];
