/**
 * IFCViewerPanel.tsx
 * ==================
 * Renders the project IFC file in a Three.js scene using web-ifc directly.
 * No external viewer wrapper — full control, no Three.js version conflicts.
 *
 * IFC file: /generated/hauskompass_lod2_baseline.ifc
 *           (generated by utils/export_ifc.py → public/generated/)
 * WASM:     /wasm/ (local web-ifc runtime assets)
 *
 * Pipeline: fetch IFC → IfcAPI.OpenModel → StreamAllMeshes
 *   → per mesh: GetGeometry → interleaved vertex buffer [pos+normal]
 *   → THREE.BufferGeometry → MeshPhongMaterial with IFC colour
 *   → apply flatTransformation → add to Three.js scene
 *
 * Layout: ifc-workspace-root → responsive ifc-viewport (full Building tab height)
 *   + collapsible ifc-info-drawer overlay
 *   + compact ifc-toolbar with framing, named presets, display modes and focus mode
 *
 * Source/uncertainty context is always visible.
 * This model is generated LoD2/DGM1 geometry — not measured as-built.
 */

import { assessmentDerivedData } from '@/features/assessment/generated/assessmentDerivedData';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

const IFC_FILE_URL = '/generated/hauskompass_lod2_baseline.ifc';
const WASM_PATH = '/wasm/';

type LoadState = 'idle' | 'fetching' | 'parsing' | 'ready' | 'error';
type ColorMode = 'type' | 'original';
type ElementKind = 'wall' | 'roof' | 'window' | 'ground' | 'terrain' | 'other';
type PresetName = 'oblique' | 'top' | 'south' | 'east' | 'west';

const { confirmedObject } = assessmentDerivedData;
const p1 = confirmedObject.parts[0];
const p2 = confirmedObject.parts[1];

const TYPE_COLORS: Record<ElementKind, { label: string; color: string }> = {
    wall: { label: 'Mauerwerk', color: '#8a7060' },
    roof: { label: 'Dachkonstruktion', color: '#c8862a' },
    window: { label: 'Dachfenster', color: '#7fd8ff' },
    ground: { label: 'Bodenplatte', color: '#5a5a4a' },
    terrain: { label: 'Gelände TIN', color: '#4a7a5a' },
    other: { label: 'Sonstiges', color: '#555555' },
};

// Edge line colours per element kind — improve category boundaries without overpowering faces
const EDGE_COLORS: Record<ElementKind, string> = {
    wall: '#c0a090', roof: '#e8ba5a', window: '#d8f3ff',
    ground: '#7a7a64', other: '#666666', terrain: '#000000',
};

const INFO_ROWS = [
    { label: 'Teil 1 — Bodenhöhe', value: `${p1.groundElevationM.toFixed(2)} m`, color: '#e07b39' },
    { label: 'Teil 1 — Gesamthöhe', value: `${p1.measuredHeightM.toFixed(2)} m`, color: '#e07b39' },
    { label: 'Teil 1 — Grundfläche', value: `${p1.groundAreaM2.toFixed(1)} m²`, color: '#e07b39' },
    { label: 'Teil 1 — Dachfläche', value: `${p1.roofAreaM2.toFixed(1)} m²`, color: '#e07b39' },
    { label: 'Teil 2 — Bodenhöhe', value: `${p2.groundElevationM.toFixed(2)} m`, color: '#4a90d9' },
    { label: 'Teil 2 — Gesamthöhe', value: `${p2.measuredHeightM.toFixed(2)} m`, color: '#4a90d9' },
    { label: 'Teil 2 — Grundfläche', value: `${p2.groundAreaM2.toFixed(1)} m²`, color: '#4a90d9' },
    { label: 'Teil 2 — Dachfläche', value: `${p2.roofAreaM2.toFixed(1)} m²`, color: '#4a90d9' },
    { label: 'Boden Δ (Teil 2 − 1)', value: `+${(p2.groundElevationM - p1.groundElevationM).toFixed(2)} m`, color: '#ccc' },
    { label: 'Gelände-Mesh', value: '966 Dreiecke · DGM1 8m TIN', color: '#7aad7a' },
    { label: 'Koordinatensystem', value: 'Lokal projiziert (UTM32N)', color: '#888' },
    { label: 'Standardansicht', value: 'Axonometrie · Teil 1 + Teil 2', color: '#6ee7b7' },
];

// Named camera preset directions — reuse visible-mesh bounding-box fit logic
const PRESET_DIRS: Record<PresetName, THREE.Vector3> = {
    oblique: new THREE.Vector3(0.62, 0.38, 0.69).normalize(),
    top: new THREE.Vector3(0.001, 1, 0).normalize(),       // near-vertical; slight offset avoids gimbal flip
    south: new THREE.Vector3(0, 0.18, 1).normalize(),      // looking north from south face
    east: new THREE.Vector3(1, 0.18, 0).normalize(),       // looking west from east face
    west: new THREE.Vector3(-1, 0.18, 0).normalize(),      // looking east from west face
};

// ── Three.js helpers ───────────────────────────────────────────────────────

function initScene(): THREE.Scene {
    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x111827);
    scene.fog = new THREE.FogExp2(0x111827, 0.008);
    scene.add(new THREE.AmbientLight(0xffffff, 0.55));
    const sun = new THREE.DirectionalLight(0xffeedd, 0.9);
    sun.position.set(20, 35, 15);
    scene.add(sun);
    const fill = new THREE.DirectionalLight(0xaabbff, 0.35);
    fill.position.set(-15, 10, -20);
    scene.add(fill);
    const grid = new THREE.GridHelper(120, 40, 0x1f2937, 0x1f2937);
    (grid.material as THREE.Material).opacity = 0.5;
    (grid.material as THREE.Material).transparent = true;
    scene.add(grid);
    return scene;
}

function buildGeom(
    verts: Float32Array,
    indices: Uint32Array,
    transform: number[] | Float32Array,
): THREE.BufferGeometry {
    // web-ifc interleaved layout: [x, y, z, nx, ny, nz, ...]
    const n = verts.length / 6;
    const pos = new Float32Array(n * 3);
    const nor = new Float32Array(n * 3);
    for (let i = 0; i < n; i++) {
        pos[i * 3] = verts[i * 6];
        pos[i * 3 + 1] = verts[i * 6 + 1];
        pos[i * 3 + 2] = verts[i * 6 + 2];
        nor[i * 3] = verts[i * 6 + 3];
        nor[i * 3 + 1] = verts[i * 6 + 4];
        nor[i * 3 + 2] = verts[i * 6 + 5];
    }
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    g.setAttribute('normal', new THREE.BufferAttribute(nor, 3));
    g.setIndex(new THREE.BufferAttribute(indices, 1));
    g.applyMatrix4(new THREE.Matrix4().fromArray(transform as number[]));
    return g;
}

// ── Component ──────────────────────────────────────────────────────────────

export function IFCViewerPanel({ ifcContent }: { ifcContent?: string }) {
    const wrapRef = useRef<HTMLDivElement>(null);
    // fitFromDirRef is populated inside the main useEffect after the scene is set up
    const fitFromDirRef = useRef<(dir: THREE.Vector3) => void>(() => { });
    // activeDirRef tracks the last-used preset direction so re-fits after visibility changes use it
    const activeDirRef = useRef<THREE.Vector3>(PRESET_DIRS.oblique);
    const meshRefs = useRef<Array<{
        mesh: THREE.Mesh;
        edgeLines?: THREE.LineSegments;
        kind: ElementKind;
        original: { r: number; g: number; b: number; a: number };
        isStageElement: boolean;
    }>>([]);

    const [loadState, setLoadState] = useState<LoadState>('idle');
    const [loadMsg, setLoadMsg] = useState('');
    const [meshCount, setMeshCount] = useState(0);
    const [colorMode, setColorMode] = useState<ColorMode>('type');
    const [showStage, setShowStage] = useState(true);
    const [showInfo, setShowInfo] = useState(false);
    const [showLegend, setShowLegend] = useState(true);
    const [focusMode, setFocusMode] = useState(false);
    const [activePreset, setActivePreset] = useState<PresetName>('oblique');

    // Escape key exits focus mode
    useEffect(() => {
        if (!focusMode) return;
        const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') setFocusMode(false); };
        document.addEventListener('keydown', handler);
        return () => document.removeEventListener('keydown', handler);
    }, [focusMode]);

    // ── Three.js scene setup + IFC load ──────────────────────────────────
    useEffect(() => {
        const wrap = wrapRef.current;
        if (!wrap) return;
        let cancelled = false;
        meshRefs.current = [];

        const scene = initScene();
        const renderer = new THREE.WebGLRenderer({ antialias: true });
        renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
        renderer.setSize(wrap.clientWidth || 800, wrap.clientHeight || 520);
        wrap.appendChild(renderer.domElement);

        const camera = new THREE.PerspectiveCamera(
            45,
            (wrap.clientWidth || 800) / (wrap.clientHeight || 520),
            0.1, 500,
        );
        camera.position.set(40, 30, 50);
        camera.lookAt(0, 8, 0);

        const controls = new OrbitControls(camera, renderer.domElement);
        controls.enableDamping = true;
        controls.dampingFactor = 0.08;
        controls.minDistance = 3;
        controls.maxDistance = 200;
        controls.target.set(0, 8, 0);
        controls.update();

        // Parameterised fit — reused by all camera presets and post-visibility re-frames
        const fitFromDir = (dir: THREE.Vector3) => {
            const box = new THREE.Box3();
            // Exclude terrain from fit — the DGM TIN is much larger than the building
            // and would push the camera so far out the building becomes invisible
            meshRefs.current.forEach(({ mesh, kind }) => {
                if (mesh.visible && kind !== 'terrain') box.expandByObject(mesh);
            });
            // Fallback: include terrain if nothing else is visible, but clamp to a sane radius
            if (box.isEmpty()) {
                meshRefs.current.forEach(({ mesh }) => {
                    if (mesh.visible) box.expandByObject(mesh);
                });
            }
            if (box.isEmpty()) box.setFromObject(scene);
            if (box.isEmpty()) return;
            const ctr = box.getCenter(new THREE.Vector3());
            const size = box.getSize(new THREE.Vector3());
            const maxDim = Math.max(size.x, size.y, size.z, 1);
            const fov = THREE.MathUtils.degToRad(camera.fov);
            const distance = (maxDim / (2 * Math.tan(fov / 2))) * 1.55;
            const target = ctr.clone();
            target.y += size.y * 0.05;
            controls.target.copy(target);
            camera.position.copy(target).add(dir.clone().multiplyScalar(distance));
            camera.near = Math.max(distance / 100, 0.1);
            camera.far = distance * 8;
            camera.updateProjectionMatrix();
            controls.update();
        };
        fitFromDirRef.current = fitFromDir;

        // ResizeObserver keeps the renderer in sync with the responsive CSS layout
        const ro = new ResizeObserver(() => {
            if (cancelled) return;
            const nw = wrap.clientWidth, nh = wrap.clientHeight;
            if (nw > 0 && nh > 0) {
                renderer.setSize(nw, nh);
                camera.aspect = nw / nh;
                camera.updateProjectionMatrix();
            }
        });
        ro.observe(wrap);

        let raf: number;
        const animate = () => {
            raf = requestAnimationFrame(animate);
            controls.update();
            renderer.render(scene, camera);
        };
        animate();

        // ── IFC load ──────────────────────────────────────────────────────
        (async () => {
            setLoadState('fetching');
            let buf: ArrayBuffer;
            try {
                if (ifcContent) {
                    setLoadMsg('Encoding generated IFC…');
                    buf = new TextEncoder().encode(ifcContent).buffer;
                } else {
                    setLoadMsg('Downloading IFC…');
                    const r = await fetch(IFC_FILE_URL);
                    if (!r.ok) throw new Error(`HTTP ${r.status} fetching ${IFC_FILE_URL}`);
                    buf = await r.arrayBuffer();
                }
            } catch (e: unknown) {
                if (!cancelled) { setLoadState('error'); setLoadMsg(String(e)); }
                return;
            }

            setLoadState('parsing');
            setLoadMsg('Parsing IFC geometry…');
            try {
                const WebIFC = await import('web-ifc');
                if (cancelled) return;

                const api = new WebIFC.IfcAPI();
                api.SetWasmPath(WASM_PATH);
                await api.Init();

                const mid = api.OpenModel(new Uint8Array(buf), {
                    COORDINATE_TO_ORIGIN: false,
                });
                const typeMap = buildElementTypeMap(api, WebIFC, mid);

                const geomCache = new Map<number, { v: Float32Array; i: Uint32Array }>();
                let count = 0;

                api.StreamAllMeshes(mid, (ifcMesh) => {
                    if (cancelled) return;
                    const geoms = ifcMesh.geometries;
                    for (let i = 0; i < geoms.size(); i++) {
                        const pg = geoms.get(i);
                        const c = pg.color;
                        const gid = pg.geometryExpressID;
                        if (!geomCache.has(gid)) {
                            const g = api.GetGeometry(mid, gid);
                            const vp = g.GetVertexData(), vs = g.GetVertexDataSize();
                            const ip = g.GetIndexData(), is = g.GetIndexDataSize();
                            geomCache.set(gid, {
                                v: ifcApi_GetVertexArray(api, vp, vs),
                                i: ifcApi_GetIndexArray(api, ip, is),
                            });
                            g.delete();
                        }
                        const { v, i: idx } = geomCache.get(gid)!;
                        if (!idx.length) continue;
                        const geo = buildGeom(v, idx, pg.flatTransformation);
                        const original = { r: c?.x ?? 0.7, g: c?.y ?? 0.7, b: c?.z ?? 0.7, a: c?.w ?? 1 };
                        const kind = typeMap.get(ifcMesh.expressID) ?? 'other';
                        const line = api.GetLine(mid, ifcMesh.expressID) as { Name?: { value?: string } } | null;
                        const name = line?.Name?.value ?? '';
                        const isStageElement = name.includes('_STAGE_') || name.startsWith('GAUBE_STAGE_');
                        const isWindow = kind === 'window';
                        const material = new THREE.MeshPhongMaterial({
                            color: new THREE.Color(TYPE_COLORS[kind].color),
                            emissive: new THREE.Color(isWindow ? '#214a5f' : '#000000'),
                            opacity: isWindow ? 0.96 : original.a,
                            transparent: isWindow || original.a < 0.99,
                            side: THREE.DoubleSide,
                            shininess: isWindow ? 70 : 20,
                        });
                        const mesh = new THREE.Mesh(geo, material);
                        mesh.visible = isStageElement ? showStage : !(showStage && kind === 'roof');

                        // Edge lines for walls, roofs, windows and ground — not terrain (too many TIN edges)
                        let edgeLines: THREE.LineSegments | undefined;
                        if (kind !== 'terrain') {
                            const edges = new THREE.EdgesGeometry(geo, 20);
                            const edgeMat = new THREE.LineBasicMaterial({
                                color: EDGE_COLORS[kind],
                                transparent: kind === 'window',
                                opacity: kind === 'window' ? 0.9 : 0.55,
                            });
                            edgeLines = new THREE.LineSegments(edges, edgeMat);
                            edgeLines.visible = mesh.visible;
                            scene.add(edgeLines);
                        }

                        meshRefs.current.push({ mesh, edgeLines, kind, original, isStageElement });
                        scene.add(mesh);
                        count++;
                    }
                });

                api.CloseModel(mid);

                if (!cancelled) {
                    setMeshCount(count);
                    setLoadState('ready');
                    setLoadMsg('');
                    fitFromDir(PRESET_DIRS.oblique);
                    fitFromDirRef.current = fitFromDir;
                    // Re-fit after React commits the "ready" state: the overlay removal and toolbar
                    // rendering may shift canvas dimensions. Two rAF ticks ensure layout is stable.
                    const scheduleRefit = () => {
                        requestAnimationFrame(() => {
                            requestAnimationFrame(() => {
                                if (!cancelled) fitFromDir(PRESET_DIRS.oblique);
                            });
                        });
                    };
                    scheduleRefit();
                }
            } catch (e: unknown) {
                if (!cancelled) { setLoadState('error'); setLoadMsg(String(e)); }
            }
        })();

        return () => {
            cancelled = true;
            cancelAnimationFrame(raf);
            controls.dispose();
            ro.disconnect();
            renderer.dispose();
            if (wrap.contains(renderer.domElement)) wrap.removeChild(renderer.domElement);
            scene.traverse(o => {
                if (o instanceof THREE.Mesh) {
                    o.geometry?.dispose();
                    (Array.isArray(o.material) ? o.material : [o.material]).forEach(m => m?.dispose());
                }
                if (o instanceof THREE.LineSegments) {
                    o.geometry?.dispose();
                    (Array.isArray(o.material) ? o.material : [o.material]).forEach(m => m?.dispose());
                }
            });
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // ── Color mode effect ────────────────────────────────────────────────
    useEffect(() => {
        meshRefs.current.forEach(({ mesh, edgeLines, kind, original }) => {
            const material = mesh.material;
            if (!(material instanceof THREE.MeshPhongMaterial)) return;
            if (colorMode === 'type') {
                material.color.set(TYPE_COLORS[kind].color);
                material.emissive.set(kind === 'window' ? '#214a5f' : '#000000');
                material.opacity = kind === 'window' ? 0.96 : original.a;
                material.transparent = kind === 'window' || original.a < 0.99;
            } else {
                material.color.setRGB(original.r, original.g, original.b);
                material.emissive.set(kind === 'window' ? '#214a5f' : '#000000');
                material.opacity = kind === 'window' ? 0.96 : original.a;
                material.transparent = kind === 'window' || original.a < 0.99;
            }
            material.needsUpdate = true;
            if (edgeLines) edgeLines.visible = mesh.visible;
        });
    }, [colorMode]);

    // ── Visibility effect — re-frames to active preset direction ─────────
    useEffect(() => {
        meshRefs.current.forEach(({ mesh, edgeLines, kind, isStageElement }) => {
            mesh.visible = isStageElement ? showStage : !(showStage && kind === 'roof');
            if (edgeLines) edgeLines.visible = mesh.visible;
        });
        fitFromDirRef.current(activeDirRef.current);
    }, [showStage]);

    // ── Camera preset handler ────────────────────────────────────────────
    const handlePreset = (preset: PresetName) => {
        setActivePreset(preset);
        activeDirRef.current = PRESET_DIRS[preset];
        fitFromDirRef.current(PRESET_DIRS[preset]);
    };

    // Fit button always re-frames to current activeDirRef (no preset state change needed)
    const handleFit = () => {
        fitFromDirRef.current(activeDirRef.current);
    };

    const isLoading = loadState === 'idle' || loadState === 'fetching' || loadState === 'parsing';

    // ── JSX ──────────────────────────────────────────────────────────────
    return (
        <div className={`ifc-workspace-root${focusMode ? ' ifc-focus-mode' : ''}`}>
            <div className="ifc-viewport">
                {/* Three.js canvas mount point */}
                <div ref={wrapRef} className="ifc-canvas-wrap" />

                {/* Loading overlay */}
                {isLoading && (
                    <div className="ifc-overlay">
                        <div className="ifc-spinner" />
                        <span className="ifc-overlay-msg">
                            {loadState === 'idle' ? 'Initialising…' : loadMsg}
                        </span>
                        <span className="ifc-overlay-sub">{IFC_FILE_URL}</span>
                    </div>
                )}

                {/* Error overlay */}
                {loadState === 'error' && (
                    <div className="ifc-overlay ifc-overlay-error">
                        <span className="ifc-overlay-error-head">Failed to load IFC</span>
                        <span className="ifc-overlay-msg">{loadMsg}</span>
                        <span className="ifc-overlay-sub">
                            Run: <code className="ifc-code">.venv/bin/python utils/export_ifc.py</code>
                        </span>
                    </div>
                )}

                {/* Ready state — toolbar, legend, badge, info drawer */}
                {loadState === 'ready' && (
                    <>
                        {/* Compact overlay toolbar — left: framing/presets, right: modes + focus */}
                        <div className="ifc-toolbar" role="toolbar" aria-label="IFC viewer controls">
                            <div className="ifc-toolbar-group">
                                <button
                                    className="ifc-tool-btn"
                                    onClick={handleFit}
                                    title="Sichtbare Geometrie einpassen — axonometrisch"
                                    type="button"
                                >
                                    Einpassen
                                </button>
                                <button
                                    className={`ifc-tool-btn${activePreset === 'top' ? ' ifc-tool-btn-active' : ''}`}
                                    onClick={() => handlePreset('top')}
                                    title="Draufsicht (Grundriss)"
                                    type="button"
                                >
                                    Oben
                                </button>
                                <button
                                    className={`ifc-tool-btn${activePreset === 'east' ? ' ifc-tool-btn-active' : ''}`}
                                    onClick={() => handlePreset('east')}
                                    title="Ostansicht"
                                    type="button"
                                >
                                    Ost
                                </button>
                                <button
                                    className={`ifc-tool-btn${activePreset === 'south' ? ' ifc-tool-btn-active' : ''}`}
                                    onClick={() => handlePreset('south')}
                                    title="Südansicht"
                                    type="button"
                                >
                                    Süd
                                </button>
                                <button
                                    className={`ifc-tool-btn${activePreset === 'west' ? ' ifc-tool-btn-active' : ''}`}
                                    onClick={() => handlePreset('west')}
                                    title="Westansicht"
                                    type="button"
                                >
                                    West
                                </button>
                            </div>
                            <div className="ifc-toolbar-group">
                                <button
                                    className={`ifc-tool-btn${showStage ? ' ifc-tool-btn-on' : ''}`}
                                    onClick={() => setShowStage((s) => !s)}
                                    title={showStage ? 'Planungsgeometrie ausblenden (nur Bestand)' : 'Planungsgeometrie einblenden'}
                                    type="button"
                                >
                                    {showStage ? '+Planung' : 'Bestand'}
                                </button>
                                <button
                                    className={`ifc-tool-btn${colorMode === 'type' ? ' ifc-tool-btn-on' : ''}`}
                                    onClick={() => setColorMode((m) => (m === 'type' ? 'original' : 'type'))}
                                    title="Toggle element colour mode"
                                    type="button"
                                >
                                    {colorMode === 'type' ? 'Typfarben' : 'IFC-Farben'}
                                </button>
                                <button
                                    className={`ifc-tool-btn${showLegend ? ' ifc-tool-btn-on' : ''}`}
                                    onClick={() => setShowLegend((s) => !s)}
                                    title="Toggle legend"
                                    type="button"
                                >
                                    Legende
                                </button>
                                <button
                                    className={`ifc-tool-btn${showInfo ? ' ifc-tool-btn-on' : ''}`}
                                    onClick={() => setShowInfo((s) => !s)}
                                    title="Toggle model info"
                                    type="button"
                                >
                                    Modellinfo
                                </button>
                                <button
                                    className={`ifc-tool-btn${focusMode ? ' ifc-tool-btn-on' : ''}`}
                                    onClick={() => setFocusMode((s) => !s)}
                                    title={focusMode ? 'Exit focus mode (Esc)' : 'Enter focus mode'}
                                    type="button"
                                >
                                    {focusMode ? '⊠ Exit' : '⊞ Focus'}
                                </button>
                            </div>
                        </div>

                        {/* Category legend — collapsible, non-obstructive bottom-left */}
                        {showLegend && (
                            <div className="ifc-legend">
                                {(['wall', 'roof', 'window', 'ground', 'terrain'] as ElementKind[]).map((kind) => (
                                    <span key={kind} className="ifc-legend-item">
                                        <i className="ifc-legend-swatch" style={{ background: TYPE_COLORS[kind].color }} />
                                        {TYPE_COLORS[kind].label}
                                    </span>
                                ))}
                            </div>
                        )}

                        {/* Source/uncertainty badge — always visible, informs viewer of data origin */}
                        <div className="ifc-source-badge">
                            {meshCount} Meshes · LoD2 + DGM1 · generiertes IFC · kein Bestandsaufmaß
                        </div>

                        {/* Collapsible info drawer — overlays the right side of the viewport */}
                        {showInfo && (
                            <div className="ifc-info-drawer">
                                <div className="ifc-info-head">
                                    Modellkontext
                                    <button
                                        className="ifc-info-close"
                                        onClick={() => setShowInfo(false)}
                                        title="Info schließen"
                                        type="button"
                                    >
                                        ×
                                    </button>
                                </div>
                                <div className="ifc-info-rows">
                                    {INFO_ROWS.map((r) => (
                                        <div key={r.label} className="ifc-info-row">
                                            <span className="ifc-info-label">{r.label}</span>
                                            <span className="ifc-info-value" style={{ color: r.color }}>{r.value}</span>
                                        </div>
                                    ))}
                                    <div className="ifc-info-row">
                                        <span className="ifc-info-label">Old / new package</span>
                                        <span className="ifc-info-value" style={{ color: showStage ? '#6ee7b7' : '#9ca3af' }}>
                                            {showStage ? '+Planung sichtbar' : 'Nur Bestand'}
                                        </span>
                                    </div>
                                </div>
                                <div className="ifc-info-footer">
                                    <div>LoD2 CityGML + DGM1 1m LiDAR</div>
                                    <div>IfcMapConversion → EPSG:25832</div>
                                    <div className="ifc-info-regenerate">
                                        Regenerate:
                                        <code>.venv/bin/python utils/export_ifc.py</code>
                                    </div>
                                </div>
                            </div>
                        )}
                    </>
                )}
            </div>
            <style>{`@keyframes ifc-spin{to{transform:rotate(360deg)}}`}</style>
        </div>
    );
}

// ── IFC type classification ────────────────────────────────────────────────

function buildElementTypeMap(api: import('web-ifc').IfcAPI, webIfc: typeof import('web-ifc'), modelId: number) {
    const typeMap = new Map<number, ElementKind>();
    for (const id of getIdSet(api, modelId, webIfc.IFCWALL)) typeMap.set(id, 'wall');
    for (const id of getIdSet(api, modelId, webIfc.IFCGEOGRAPHICELEMENT)) typeMap.set(id, 'terrain');
    for (const id of getIdSet(api, modelId, webIfc.IFCWINDOW)) typeMap.set(id, 'window');
    for (const id of getIdSet(api, modelId, webIfc.IFCSLAB)) {
        const line = api.GetLine(modelId, id) as { Name?: { value?: string } } | null;
        const name = line?.Name?.value?.toLowerCase() ?? '';
        typeMap.set(id, name.includes('roof') ? 'roof' : 'ground');
    }
    return typeMap;
}

function getIdSet(api: import('web-ifc').IfcAPI, modelId: number, type: number) {
    const ids = api.GetLineIDsWithType(modelId, type) as { size(): number; get(index: number): number };
    const list: number[] = [];
    for (let i = 0; i < ids.size(); i++) list.push(ids.get(i));
    return list;
}

// web-ifc typed wrappers (avoid 'any' casts in the hot path)
function ifcApi_GetVertexArray(api: import('web-ifc').IfcAPI, ptr: number, size: number): Float32Array {
    return (api as unknown as { GetVertexArray(p: number, s: number): Float32Array }).GetVertexArray(ptr, size);
}
function ifcApi_GetIndexArray(api: import('web-ifc').IfcAPI, ptr: number, size: number): Uint32Array {
    return (api as unknown as { GetIndexArray(p: number, s: number): Uint32Array }).GetIndexArray(ptr, size);
}


